services:
  nginx:
    pull_policy: never
    build:
      dockerfile: containers/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      FPM_HOST: php
      FPM_PORT: 9000
  php:
    pull_policy: never
    build:
      dockerfile: containers/php/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www/html
