services:
  testing:
    build:
      dockerfile: containers/php/Dockerfile
      context: .
      target: testing
      cache_to:
        - type=gha,mode=max,scope=testing
      cache_from:
        - type=gha,scope=testing
