x-app: &app
  pull_policy: never
  build:
    dockerfile: containers/php/Dockerfile
    target: development
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
  restart: unless-stopped
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - .:/var/www/html
  env_file:
    - .env

services:
  nginx:
    pull_policy: never
    build:
      dockerfile: containers/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      FPM_HOST: php
      FPM_PORT: 9000
  php:
    <<: *app
    environment:
      NIGHTWATCH_INGEST_URI: nightwatch-agent:2407
  scheduler:
    <<: *app
    user: root
    command: scheduler
    stop_signal: SIGKILL
    environment:
      PHP_HOST: php
      PHP_PORT: 9000
  worker:
    <<: *app
    user: root
    command: worker
    environment:
      PHP_HOST: php
      PHP_PORT: 9000
  nightwatch-agent:
    <<: *app
    user: root
    command: nightwatch
    stop_signal: SIGKILL
    environment:
      PHP_HOST: php
      PHP_PORT: 9000
    healthcheck:
      test: php artisan nightwatch:status
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis:
    image: redis:8.2.1-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  testing:
    profiles:
      - testing
    build:
      dockerfile: containers/php/Dockerfile
      context: .
      target: testing
      cache_to:
        - type=gha,mode=max,scope=testing
      cache_from:
        - type=gha,scope=testing

