services:
  app:
    pull_policy: never
    build:
      dockerfile: containers/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www/html
