services:
  nginx:
    pull_policy: never
    build:
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "8080:80"
    environment:
      FPM_HOST: php
      FPM_PORT: 9000
  php:
    pull_policy: never
    build:
      dockerfile: containers/php/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/var/www/html
  worker:
    extends:
      service: php
    stop_signal: SIGKILL
    command: php artisan queue:listen --tries=3 --timeout=1800
    environment:
      PHP_HOST: php
      PHP_PORT: 9000
  scheduler:
    extends:
      service: php
    stop_signal: SIGKILL
    command: crond -f
    environment:
      PHP_HOST: php
      PHP_PORT: 9000
