name: parceler-prod
services:
  nginx:
    image: ghcr.io/nethesis/parceler-nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      FPM_HOST: php
      FPM_PORT: 9000
  php:
    image: ghcr.io/nethesis/parceler-php:latest
    volumes:
      - storage:/var/www/html/storage
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: rclone
        target: /var/www/html/rclone.conf
    env_file:
      - .env
  worker:
    extends:
      service: php
    stop_signal: SIGKILL
    command: worker
    environment:
      PHP_HOST: php
      PHP_PORT: 9000
  scheduler:
    extends:
      service: php
    stop_signal: SIGKILL
    command: scheduler
    environment:
      PHP_HOST: php
      PHP_PORT: 9000

volumes:
  storage: { }

configs:
  rclone:
    file: rclone.conf
