name: Build

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta-php
        with:
          bake-target: php
          images: |
            ghcr.io/${{ github.repository }}-php
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/metadata-action@v5
        id: meta-nginx
        with:
          bake-target: nginx
          images: |
            ghcr.io/${{ github.repository }}-nginx
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/bake-action@v6
        with:
          targets: production
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-php.outputs.bake-file }}
            ${{ steps.meta-nginx.outputs.bake-file }}
          sbom: true
          provenance: true
          push: true

      - name: Generate SBOM for php
        uses: anchore/sbom-action@v0
        with:
          image: ${{ fromJSON(steps.meta-php.outputs.json).tags[0] }}
          output-file: php-sbom.spdx.json
          dependency-snapshot: true
      - name: Scan php
        uses: anchore/scan-action@v6
        id: php-scan
        with:
          sbom: php-sbom.spdx.json
          fail-build: false
      - name: Upload report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.php-scan.outputs.sarif }}
          category: grype-php-report

      - name: Generate SBOM for nginx
        uses: anchore/sbom-action@v0
        with:
          image: ${{ fromJSON(steps.meta-nginx.outputs.json).tags[0] }}
          output-file: nginx-sbom.spdx.json
          dependency-snapshot: true
      - name: Scan nginx
        uses: anchore/scan-action@v6
        id: nginx-scan
        with:
          sbom: nginx-sbom.spdx.json
          fail-build: false
      - name: Upload report to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.nginx-scan.outputs.sarif }}
          category: grype-nginx-report
