name: Build

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta-php
        with:
          bake-target: php
          images: |
            ghcr.io/${{ github.repository }}-php
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/metadata-action@v5
        id: meta-nginx
        with:
          bake-target: nginx
          images: |
            ghcr.io/${{ github.repository }}-nginx
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/bake-action@v5
        with:
          targets: production
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-php.outputs.bake-file }}
            ${{ steps.meta-nginx.outputs.bake-file }}
          sbom: true
          provenance: true
          push: true
