name: Build

on:
  push:
    branches:
      - main
    tags:
      - "**"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Generate tags
        uses: docker/metadata-action@v5
        id: meta
        with:
          bake-target: production
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/bake-action@v4
        with:
          targets: production
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha
            *.output=type=registry
