name: CI

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  pint:
    name: Pint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker compose -f docker-compose.testing.yml run --rm testing ./vendor/bin/pint --test
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    uses: ./.github/workflows/build.yml
