name: CI

on:
  push:
    branches-ignore:
      - main
      - renovate/**
      - release-**
  pull_request:
    branches-ignore:
      - renovate/**
      - release-**
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    uses: ./.github/workflows/build.yml
