name: CI

on:
  pull_request:
    branches-ignore:
      - renovate/**
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    needs: test
    uses: ./.github/workflows/build.yml
